CREATE TABLE delivery_letter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    letter_id UUID NOT NULL UNIQUE,
    getter_id UUID NOT NULL,
    getter_type VARCHAR(25) NOT NULL,
    letter_status VARCHAR(25)
);

CREATE TABLE delivery_letter_status (
    status_id UUID PRIMARY KEY,
    created_time TIMESTAMP NOT NULL,
    delivery_status VARCHAR(25) NOT NULL,
    delivery_letter_id BIGINT NOT NULL,

    CONSTRAINT fk_delivery_letter_status_delivery_letter FOREIGN KEY (delivery_letter_id)
                REFERENCES delivery_letter(id) ON DELETE CASCADE
);

CREATE TABLE event_outbox (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_name VARCHAR(50) NOT NULL,
    letter_id UUID NOT NULL UNIQUE,
    getter_id UUID NOT NULL,
    getter_type VARCHAR(25) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    status VARCHAR(25)
);

CREATE INDEX idx_status_eventId ON event_outbox(status, event_id);
