server:
  port: ${PORT:0}

spring:
  jpa:
    properties:
      hibernate:
        default_schema: public
    show-sql: ${SHOW_SQL:false}
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/mail_delivery?currentSchema=public
    username: postgres
    password: 123
  liquibase:
    default-schema: public
    change-log: classpath:db/changelog-master.xml
  kafka:
    bootstrap-servers: ${KAFKA_CONTROL_BOOTSTRAP_SERVERS:localhost:9096}
    consumer:
      group-id: ${KAFKA_CONTROL_GROUP_ID:delivery-group}
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        batch.size: 131072 # 128 KB
        compression.type: snappy
        linger.ms: 50
        max.block.ms: 10000
        request.timeout.ms: 15000
        delivery.timeout.ms: 120000
    listener:
      type: single
      auto-startup: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8762/eureka}

app:
  outbox:
    scheduler:
      ready: PT1M
      prepare: PT10S
      expired: PT24H
  kafka:
    topics:
      delivery-topic: ${DELIVERY_TOPIC:delivery-letter}
      delivery-topic-dlt: ${DELIVERY_TOPIC:delivery-letter-dlt}
      get-topic: ${GET_LETTER_TOPIC:get-letter}
